/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CompilerRouteImport } from './routes/compiler'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ReviewResultsRouteImport } from './routes/review-results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompilerRoute = CompilerRouteImport.update({
  id: '/compiler',
  path: '/compiler',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewResultsRoute = ReviewResultsRouteImport.update({
  id: '/review-results',
  path: '/review-results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compiler': typeof CompilerRoute
  '/how-it-works': typeof HowItWorksRoute
  '/review-results': typeof ReviewResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compiler': typeof CompilerRoute
  '/how-it-works': typeof HowItWorksRoute
  '/review-results': typeof ReviewResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compiler': typeof CompilerRoute
  '/how-it-works': typeof HowItWorksRoute
  '/review-results': typeof ReviewResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/compiler' | '/how-it-works' | '/review-results'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/compiler' | '/how-it-works' | '/review-results'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compiler'
    | '/how-it-works'
    | '/review-results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompilerRoute: typeof CompilerRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ReviewResultsRoute: typeof ReviewResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compiler': {
      id: '/compiler'
      path: '/compiler'
      fullPath: '/compiler'
      preLoaderRoute: typeof CompilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-results': {
      id: '/review-results'
      path: '/review-results'
      fullPath: '/review-results'
      preLoaderRoute: typeof ReviewResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompilerRoute: CompilerRoute,
  HowItWorksRoute: HowItWorksRoute,
  ReviewResultsRoute: ReviewResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
